import { NextResponse } from "next/server";
import Item from "@/database/models/item.modal";
import { dbConnect } from "@/database/dbConnect";

const items = [
  {
    name: "Garden Fresh Salad",
    category: "Appetizers",
    diet: "Vegetarian",
    price: 180,
    description: "Crispy lettuce, cherry tomatoes, and cucumber with house dressing.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    isSpecial: true,
  },
  {
    name: "Spicy Chicken Wings",
    category: "Appetizers",
    diet: "Non-Vegetarian",
    price: 240,
    description: "Crispy chicken wings tossed in our signature spicy sauce.",
    image: "https://images.unsplash.com/photo-1606756790138-268a3f2a0c49",
    isSpecial: false,
  },
  {
    name: "Vegan Buddha Bowl",
    category: "Main Course",
    diet: "Vegan",
    price: 360,
    description: "Brown rice, tofu, chickpeas, and veggies with tahini dressing.",
    image: "https://images.unsplash.com/photo-1601050690597-6c0d9b9cfb6a",
    isSpecial: true,
  },
  {
    name: "Grilled Fish with Lemon Butter",
    category: "Main Course",
    diet: "Non-Vegetarian",
    price: 480,
    description: "Grilled fish fillet with lemon butter sauce and herbs.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    isSpecial: false,
  },
  {
    name: "Paneer Butter Masala",
    category: "Main Course",
    diet: "Vegetarian",
    price: 350,
    description: "Soft paneer cubes simmered in a buttery tomato gravy.",
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
    isSpecial: false,
  },
  {
    name: "Chocolate Lava Cake",
    category: "Desserts",
    diet: "Vegetarian",
    price: 210,
    description: "Warm chocolate cake with a molten chocolate center.",
    image: "https://images.unsplash.com/photo-1604152135912-04a022e23696",
    isSpecial: true,
  },
  {
    name: "Mango Cheesecake",
    category: "Desserts",
    diet: "Vegetarian",
    price: 250,
    description: "Smooth mango cheesecake on a buttery biscuit base.",
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
    isSpecial: false,
  },
  {
    name: "Classic Mojito",
    category: "Beverages",
    diet: "Vegan",
    price: 160,
    description: "Refreshing mint and lime cooler served chilled.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    isSpecial: false,
  },
  {
    name: "Cold Coffee Frappe",
    category: "Beverages",
    diet: "Vegetarian",
    price: 180,
    description: "Iced coffee blended with milk, sugar, and cream.",
    image: "https://images.unsplash.com/photo-1576711640795-1cb2f8e6aeb8",
    isSpecial: true,
  },
  {
    name: "Gluten-Free Pancakes",
    category: "Desserts",
    diet: "Gluten-Free",
    price: 220,
    description: "Fluffy pancakes with honey drizzle and fruit toppings.",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90",
    isSpecial: false,
  },
  {
    name: "Falafel Wrap",
    category: "Appetizers",
    diet: "Vegan",
    price: 190,
    description: "Crispy falafels wrapped with veggies and tahini sauce.",
    image: "https://images.unsplash.com/photo-1601050690597-6c0d9b9cfb6a",
    isSpecial: false,
  },
  {
    name: "Butter Chicken",
    category: "Main Course",
    diet: "Non-Vegetarian",
    price: 420,
    description: "Tender chicken cooked in rich buttery tomato gravy.",
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
    isSpecial: true,
  },
  {
    name: "Caesar Salad",
    category: "Appetizers",
    diet: "Vegetarian",
    price: 200,
    description: "Classic Caesar salad with homemade dressing and croutons.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    isSpecial: false,
  },
  {
    name: "Tandoori Roti",
    category: "Main Course",
    diet: "Vegan",
    price: 160,
    description: "Whole wheat roti baked in a traditional clay oven.",
    image: "https://images.unsplash.com/photo-1601050690597-6c0d9b9cfb6a",
    isSpecial: false,
  },
  {
    name: "Berry Smoothie",
    category: "Beverages",
    diet: "Vegan",
    price: 190,
    description: "Mixed berry smoothie made with almond milk.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    isSpecial: true,
  },
  {
    name: "Chocolate Milkshake",
    category: "Beverages",
    diet: "Vegetarian",
    price: 180,
    description: "Creamy chocolate milkshake topped with whipped cream.",
    image: "https://images.unsplash.com/photo-1576711640795-1cb2f8e6aeb8",
    isSpecial: false,
  },
  {
    name: "Pasta Alfredo",
    category: "Main Course",
    diet: "Vegetarian",
    price: 380,
    description: "Creamy Alfredo pasta with mushrooms and parmesan cheese.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
    isSpecial: false,
  },
  {
    name: "Chicken Biryani",
    category: "Specials",
    diet: "Non-Vegetarian",
    price: 520,
    description: "Aromatic basmati rice cooked with chicken and Indian spices.",
    image: "https://images.unsplash.com/photo-1606756790138-268a3f2a0c49",
    isSpecial: true,
  },
  {
    name: "Vegan Brownie",
    category: "Desserts",
    diet: "Vegan",
    price: 210,
    description: "Rich chocolate brownie made with coconut oil.",
    image: "https://images.unsplash.com/photo-1604152135912-04a022e23696",
    isSpecial: false,
  },
  {
    name: "Lemon Iced Tea",
    category: "Beverages",
    diet: "Vegan",
    price: 160,
    description: "Chilled lemon tea with a hint of mint.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    isSpecial: false,
  },
];
const moreItems = [
  { name: "Veggie Spring Rolls", category: "Appetizers", diet: "Vegetarian", price: 180, description: "Crispy rolls stuffed with fresh veggies.", image: "https://source.unsplash.com/400x300/?springroll", isSpecial: false },
  { name: "Chicken Satay Skewers", category: "Appetizers", diet: "Non-Vegetarian", price: 250, description: "Grilled chicken skewers with peanut sauce.", image: "https://source.unsplash.com/400x300/?chicken,skewers", isSpecial: true },
  { name: "Vegan Tacos", category: "Main Course", diet: "Vegan", price: 320, description: "Soft tacos filled with beans, avocado, and veggies.", image: "https://source.unsplash.com/400x300/?vegan,tacos", isSpecial: false },
  { name: "Paneer Tikka Masala", category: "Main Course", diet: "Vegetarian", price: 360, description: "Paneer cooked in spiced tomato gravy.", image: "https://source.unsplash.com/400x300/?paneer", isSpecial: true },
  { name: "Grilled Salmon", category: "Main Course", diet: "Non-Vegetarian", price: 500, description: "Salmon fillet grilled with herbs and lemon.", image: "https://source.unsplash.com/400x300/?salmon", isSpecial: true },
  { name: "Mushroom Risotto", category: "Main Course", diet: "Vegetarian", price: 380, description: "Creamy risotto with mushrooms and parmesan.", image: "https://source.unsplash.com/400x300/?mushroom,risotto", isSpecial: false },
  { name: "Chocolate Brownie", category: "Desserts", diet: "Vegetarian", price: 200, description: "Rich chocolate brownie topped with nuts.", image: "https://source.unsplash.com/400x300/?brownie", isSpecial: false },
  { name: "Vanilla Ice Cream", category: "Desserts", diet: "Vegetarian", price: 180, description: "Classic creamy vanilla ice cream.", image: "https://source.unsplash.com/400x300/?icecream", isSpecial: false },
  { name: "Blueberry Cheesecake", category: "Desserts", diet: "Vegetarian", price: 250, description: "Creamy cheesecake with blueberry topping.", image: "https://source.unsplash.com/400x300/?cheesecake,blueberry", isSpecial: true },
  { name: "Mango Lassi", category: "Beverages", diet: "Vegetarian", price: 170, description: "Refreshing mango yogurt drink.", image: "https://source.unsplash.com/400x300/?mango,drink", isSpecial: false },
  { name: "Iced Lemon Tea", category: "Beverages", diet: "Vegan", price: 160, description: "Chilled lemon tea with mint.", image: "https://source.unsplash.com/400x300/?lemon,tea", isSpecial: false },
  { name: "Cold Coffee", category: "Beverages", diet: "Vegetarian", price: 180, description: "Iced coffee with milk and sugar.", image: "https://source.unsplash.com/400x300/?coldcoffee", isSpecial: true },
  { name: "Gluten-Free Pancakes", category: "Desserts", diet: "Gluten-Free", price: 220, description: "Fluffy pancakes without gluten.", image: "https://source.unsplash.com/400x300/?pancakes", isSpecial: false },
  { name: "Falafel Wrap", category: "Appetizers", diet: "Vegan", price: 190, description: "Crispy falafel with vegetables in wrap.", image: "https://source.unsplash.com/400x300/?falafel", isSpecial: false },
  { name: "Butter Chicken", category: "Main Course", diet: "Non-Vegetarian", price: 420, description: "Tender chicken in buttery tomato gravy.", image: "https://source.unsplash.com/400x300/?butter,chicken", isSpecial: true },
  { name: "Caesar Salad", category: "Appetizers", diet: "Vegetarian", price: 200, description: "Classic Caesar salad with croutons.", image: "https://source.unsplash.com/400x300/?caesar,salad", isSpecial: false },
  { name: "Tandoori Roti", category: "Main Course", diet: "Vegan", price: 160, description: "Clay-baked whole wheat roti.", image: "https://source.unsplash.com/400x300/?roti", isSpecial: false },
  { name: "Berry Smoothie", category: "Beverages", diet: "Vegan", price: 190, description: "Mixed berry smoothie with almond milk.", image: "https://source.unsplash.com/400x300/?smoothie,berry", isSpecial: true },
  { name: "Chocolate Milkshake", category: "Beverages", diet: "Vegetarian", price: 180, description: "Creamy chocolate milkshake with cream.", image: "https://source.unsplash.com/400x300/?milkshake", isSpecial: false },
  { name: "Pasta Alfredo", category: "Main Course", diet: "Vegetarian", price: 380, description: "Creamy Alfredo pasta with mushrooms.", image: "https://source.unsplash.com/400x300/?pasta,alfredo", isSpecial: false },
  { name: "Chicken Biryani", category: "Specials", diet: "Non-Vegetarian", price: 520, description: "Aromatic basmati rice with chicken.", image: "https://source.unsplash.com/400x300/?biryani", isSpecial: true },
  { name: "Vegan Brownie", category: "Desserts", diet: "Vegan", price: 210, description: "Chocolate brownie made with coconut oil.", image: "https://source.unsplash.com/400x300/?vegan,brownie", isSpecial: false },
  { name: "Lemon Iced Tea", category: "Beverages", diet: "Vegan", price: 160, description: "Chilled lemon tea with mint.", image: "https://source.unsplash.com/400x300/?lemon,icedtea", isSpecial: false },
  { name: "Grilled Vegetable Skewers", category: "Appetizers", diet: "Vegan", price: 230, description: "Assorted grilled vegetables on skewers.", image: "https://source.unsplash.com/400x300/?grilled,vegetables", isSpecial: false },
  { name: "Stuffed Mushrooms", category: "Appetizers", diet: "Vegetarian", price: 220, description: "Baked mushrooms stuffed with cheese.", image: "https://source.unsplash.com/400x300/?stuffed,mushrooms", isSpecial: true },
  { name: "Veggie Burger", category: "Main Course", diet: "Vegetarian", price: 300, description: "Grilled veggie patty in a bun.", image: "https://source.unsplash.com/400x300/?veggie,burger", isSpecial: false },
  { name: "Beef Steak", category: "Main Course", diet: "Non-Vegetarian", price: 550, description: "Grilled beef steak with herbs.", image: "https://source.unsplash.com/400x300/?beef,steak", isSpecial: true },
  { name: "Fish Curry", category: "Main Course", diet: "Non-Vegetarian", price: 450, description: "Spicy fish curry with coconut milk.", image: "https://source.unsplash.com/400x300/?fish,curry", isSpecial: false },
  { name: "Chocolate Fondant", category: "Desserts", diet: "Vegetarian", price: 230, description: "Molten chocolate cake with ice cream.", image: "https://source.unsplash.com/400x300/?chocolate,fondant", isSpecial: true },
  { name: "Carrot Halwa", category: "Desserts", diet: "Vegetarian", price: 180, description: "Traditional Indian sweet made with carrots.", image: "https://source.unsplash.com/400x300/?carrot,halwa", isSpecial: false },
  { name: "Cappuccino", category: "Beverages", diet: "Vegetarian", price: 170, description: "Espresso with steamed milk and foam.", image: "https://source.unsplash.com/400x300/?cappuccino", isSpecial: false },
  { name: "Green Tea", category: "Beverages", diet: "Vegan", price: 160, description: "Refreshing green tea.", image: "https://source.unsplash.com/400x300/?green,tea", isSpecial: false },
  { name: "Vegan Pizza", category: "Main Course", diet: "Vegan", price: 380, description: "Pizza topped with vegetables and vegan cheese.", image: "https://source.unsplash.com/400x300/?vegan,pizza", isSpecial: true },
  { name: "Paneer Kebab", category: "Appetizers", diet: "Vegetarian", price: 240, description: "Grilled paneer with spices.", image: "https://source.unsplash.com/400x300/?paneer,kebab", isSpecial: false },
  { name: "Chicken Shawarma", category: "Main Course", diet: "Non-Vegetarian", price: 400, description: "Grilled chicken with garlic sauce in pita.", image: "https://source.unsplash.com/400x300/?chicken,shawarma", isSpecial: true },
  { name: "Veggie Wrap", category: "Appetizers", diet: "Vegan", price: 200, description: "Fresh veggies wrapped in tortilla.", image: "https://source.unsplash.com/400x300/?veggie,wrap", isSpecial: false },
  { name: "Prawn Tempura", category: "Main Course", diet: "Non-Vegetarian", price: 480, description: "Deep-fried prawns in tempura batter.", image: "https://source.unsplash.com/400x300/?prawn,tempura", isSpecial: true },
  { name: "Banana Smoothie", category: "Beverages", diet: "Vegetarian", price: 170, description: "Banana blended with milk and honey.", image: "https://source.unsplash.com/400x300/?banana,smoothie", isSpecial: false },
 
  ]
export async function GET() {
  try {
    await dbConnect();

    // Delete old items if needed
    await Item.deleteMany({});

    // Insert new items
    await Item.insertMany(items);
   await Item.insertMany(moreItems);
    return NextResponse.json({ success: true, message: "Items seeded successfully!" });
  } catch (error) {
    console.error("Seeding error:", error);
    return NextResponse.json({ success: false, message: "Seeding failed." }, { status: 500 });
  }
}
