import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({subsets:['latin']})
export const metadata = {
  title: "DineNGo",
  description: "Generated by Pranav ",
};
import { useUser } from "@clerk/nextjs";
import ClientWrapper from "@/hooks/ClientWrapper";
export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
  <ClerkProvider>
      <html lang="en">
        <body  className={inter.className} >
         <ClientWrapper />
         <Header />
          {children}
          <ToastContainer />
          <Footer />
        </body>
      </html>
</ClerkProvider>
  );
}

