import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import ClientWrapper from "@/hooks/ClientWrapper";
import "leaflet/dist/leaflet.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DineNGo",
  description: "Generated by Pranav",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ClientWrapper>
            {children}
          </ClientWrapper>

          <ToastContainer position="top-right" autoClose={3000} />
        </body>
      </html>
    </ClerkProvider>
  );
}
